# Generated by Django 5.2.4 on 2025-07-15 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفرع')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الرتبه')),
            ],
        ),
        migrations.CreateModel(
            name='ArmyPerson',
            fields=[
                ('code', models.CharField(db_index=True, max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='الكود')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branch', verbose_name='الفرع')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rank', verbose_name='الرتبه')),
            ],
        ),
    ]
