# Generated by Django 5.2.4 on 2025-07-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='اسم الفرع'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='name',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='اسم الرتبه'),
        ),
    ]
