# Generated by Django 5.2.4 on 2025-07-15 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_branch_name_alter_rank_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='armyperson',
            options={'verbose_name': 'عسكرى', 'verbose_name_plural': 'العساكر'},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'فرع', 'verbose_name_plural': 'الفروع'},
        ),
        migrations.AlterModelOptions(
            name='rank',
            options={'verbose_name': 'رتبه', 'verbose_name_plural': 'الرتب'},
        ),
        migrations.CreateModel(
            name='PendingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.CharField(choices=[('انتظار', 'Pending'), ('موافق', 'Accepted'), ('تم الرفض', 'Rejected')], default='انتظار', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='core.armyperson')),
            ],
        ),
    ]
